GET http://localhost:3001/api/booking HTTP/1.1

###

POST http://localhost:3001/api/booking HTTP/1.1
content-type: application/json; charset=UTF-8

{
    "person": "test2",
    "date": "2022-10-03"
}

###

Delete http://localhost:3001/api/booking HTTP/1.1

content-type: application/json; charset=UTF-8
{
    "date": "2022-10-03",
}
