name: Build and Release

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Setup | Checkout code
        uses: actions/checkout@v3

      - name: Setup | Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build | Test
        env:
            DATABASE_SECRET: ${{ secrets.DATABASE_SECRET}}
            DATABASE_URL: ${{ secrets.DATABASE_URL}}
        run: cargo test --release       

      - name: Build and publish "latest" Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          image-name: ${{ github.event.repository.name }} 
          dockerfile: Containerfile


